headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/Users/DiceAdmin/Desktop/All Projects/cURL_kit/web/.next"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/DiceAdmin/Desktop/All Projects/cURL_kit/web"
command = "npm run build"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]